[package]
name = "vp8"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.6.0"
rand = "0.8.5"
piston_window = "0.124.0"

[profile.dev]
opt-level = 1