[package]
name = "vp8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-derive = "0.3.3"
num-traits = "0.2.15"
num = "0.4.0"
parse-display = "0.6.0"
rand = "0.8.5"